#!/bin/sh

if ! TAGS=$(git ls-remote --tags --sort="-v:refname" git@github.com:probeldev/niri-float-sticky.git 2>/dev/null); then
    VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
else
    VERSION=$(echo "$TAGS" | head -n1 | sed 's/.*\///; s/\^{}//')
fi

cat > version.go <<EOF
package main

const version = "$VERSION" // injected on pre-commit hook
EOF

git add version.go
